"""added post column

Revision ID: 0de5184abe4b
Revises: c866b38e819f
Create Date: 2021-05-01 12:14:47.337995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0de5184abe4b'
down_revision = 'c866b38e819f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('post', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'post')
    # ### end Alembic commands ###
