"""updated users table

Revision ID: 303888120ebb
Revises: 7f46e4a2d818
Create Date: 2021-05-01 17:00:38.771832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '303888120ebb'
down_revision = '7f46e4a2d818'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('writers', sa.Column('bio', sa.String(length=255), nullable=True))
    op.add_column('writers', sa.Column('image_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('writers', 'image_path')
    op.drop_column('writers', 'bio')
    # ### end Alembic commands ###
