"""fixing backrefs2

Revision ID: 5887013e1bd3
Revises: d5d6ac39c7b2
Create Date: 2021-05-02 06:09:12.419193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5887013e1bd3'
down_revision = 'd5d6ac39c7b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('writer_id', sa.Integer(), nullable=True))
    op.drop_constraint('blogs_user_id_fkey', 'blogs', type_='foreignkey')
    op.create_foreign_key(None, 'blogs', 'writers', ['writer_id'], ['id'])
    op.drop_column('blogs', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'blogs', type_='foreignkey')
    op.create_foreign_key('blogs_user_id_fkey', 'blogs', 'writers', ['user_id'], ['id'])
    op.drop_column('blogs', 'writer_id')
    # ### end Alembic commands ###
