"""added username to comment form

Revision ID: 7f46e4a2d818
Revises: c8e212c95c05
Create Date: 2021-05-01 13:53:02.245945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f46e4a2d818'
down_revision = 'c8e212c95c05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('username', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'username')
    # ### end Alembic commands ###
