"""fixing backrefsvii

Revision ID: cc62faf7a680
Revises: 84945a3715af
Create Date: 2021-05-02 06:39:25.387756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc62faf7a680'
down_revision = '84945a3715af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('writer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'blogs', 'writers', ['writer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blogs', type_='foreignkey')
    op.drop_column('blogs', 'writer_id')
    # ### end Alembic commands ###
